### ISSUE TITLE
Change the project name, so it would grow virally.

### ISSUE THREAD

**Issue by Ornataweaver** [rokist/plynth-dev#4]
I think an easy name would help the growth of the software.
Like Fiddle, check it out:
https://electronjs.org/fiddle
Do you wanna make something similar to Fiddle for python?

**Comment by rokist** [comment]
It's the same pronunciation as plinth.
We just tried to make it close to Python.
Is it consusing?
It could be renamed since it's at a very early stage.
any ideas?

**Comment by Ornataweaver** [comment]
💃 
What was in your mind?
What words does plynth include?
Describe what inspired you to make this software, so I can suggest better words for you to choose.

**Comment by Ornataweaver** [comment]
If the name wasn't related to python, it would be even prettier.
For example Django is from the name of the guitarist "Django Reinhardt".
Do you like any directors, artists, scientists, etc?

**Comment by Ornataweaver** [comment]
For example, Dali the python shell. (as in electron, the atom shell)

"Salvador Domingo Felipe Jacinto Dalí i Domènech, Marquis of Dalí de Púbol (/ˈdɑːli, dɑːˈliː/,[1][2] Catalan: [səlβəˈðo ðəˈli], Spanish: [salβaˈðoɾ ðaˈli]; 11 May 1904 – 23 January 1989) was a Spanish Surrealist artist, of Catalan ethnicity, born in Figueres, Catalonia, Spain."
from https://en.wikipedia.org/wiki/Salvador_Dalí
